# Waypoints for navigating to specific zones from center of map


#NEED TO DETERMINE THESE - CURRENTLY PLACEHOLDER VALUES
cyan:
  waypoint_1:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_2:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_3:
    x:  -3.5
    y:   0.0
    yaw: 0.0

purple:
  waypoint_1:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_2:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_3:
    x:  -3.5
    y:   0.0
    yaw: 0.0

green:
  waypoint_1:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_2:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_3:
    x:  -3.5
    y:   0.0
    yaw: 0.0

pink:
  waypoint_1:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_2:
    x:  -3.5
    y:   0.0
    yaw: 0.0
  waypoint_3:
    x:  -3.5
    y:   0.0
    yaw: 0.0


